src/Entity/Questions.php
<?php

namespace App\Entity;

use App\Repository\QuestionsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=QuestionsRepository::class)
 */
class Questions
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $libelle;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_multiple;

    /**
     * @ORM\OneToMany(targetEntity=Answers::class, mappedBy="id_question")
     */
    private $answers;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="questions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function __construct()
    {
        $this->answers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(?string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getIsMultiple(): ?bool
    {
        return $this->is_multiple;
    }

    public function setIsMultiple(?bool $is_multiple): self
    {
        $this->is_multiple = $is_multiple;

        return $this;
    }

    /**
     * @return Collection|Answers[]
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answers $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers[] = $answer;
            $answer->setIdQuestion($this);
        }

        return $this;
    }

    public function removeAnswer(Answers $answer): self
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getId() === $this) {
                $answer->setId(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;
        return $this;
    }

    public function __toString()
    {
        return $this->libelle;
    }
}

src/Form/QuestionsType.php
<?php

namespace App\Form;

use App\Entity\Questions;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QuestionsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('libelle')
            ->add('is_multiple')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Questions::class,
        ]);
    }
}

src/Controller/QuestionsController.php
<?php

namespace App\Controller;

use App\Entity\Result;
use App\Entity\Questions;
use App\Form\QuestionsType;
use App\Repository\AnswersRepository;
use App\Repository\QuestionsRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\UX\Chartjs\Builder\ChartBuilderInterface;
use Symfony\UX\Chartjs\Model\Chart;

#[Route('/questions')]
class QuestionsController extends AbstractController
{
    #[Route('/', name: 'questions_index', methods: ['GET'])]
    public function index(QuestionsRepository $questionsRepository): Response
    {
        return $this->render('questions/index.html.twig', [
            'questions' => $questionsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'questions_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $question = new Questions();
        $form = $this->createForm(QuestionsType::class, $question);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $question->setUser($this->getUser());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($question);
            $entityManager->flush();

            return $this->redirectToRoute('questions_index');
        }

        return $this->render('questions/new.html.twig', [
            'question' => $question,
            'form' => $form->createView(),
        ]);
    }

    //// a modifier ///////////
    #[Route('/result/{id}', name: 'questions_result', methods: ['GET'])]
    public function show(Questions $question): Response
    {
        return $this->render('questions/result.html.twig', [
            'question' => $question,
        ]);
    }

    #[Route('/stats', name: 'stats', methods: ['GET'])]
    public function dashboard(ChartBuilderInterface $chartBuilder)
    {
        $chart = $chartBuilder->createChart(Chart::TYPE_LINE);
        $chart->setData([
            'labels' => ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
            'datasets' => [
                [
                    'label' => 'Sales!',
                    'backgroundColor' => 'rgb(255, 99, 132)',
                    'borderColor' => 'rgb(255, 99, 132)',
                    'data' => [522, 1500, 2250, 2197, 2345, 3122, 3099],
                ],
            ],
        ]);

        return $this->render('questions/stats.html.twig', [
            'chart' => $chart
        ]);
    }

    //////////////////       //////////////////////////


    #[Route('/{id}/edit', name: 'questions_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Questions $question): Response
    {
        $form = $this->createForm(QuestionsType::class, $question);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('questions_index');
        }

        return $this->render('questions/edit.html.twig', [
            'question' => $question,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}/answer', name: 'questions_answer', methods: ['GET', 'POST'])]
    public function answer(Request $request, Questions $question,AnswersRepository $answersRepository): Response
    {
        if ($request->getMethod() === 'POST') {
            $formData = $request->request->get('answer');
            $entityManager = $this->getDoctrine()->getManager();
            foreach ($formData as $choiceId) {
                $resultat = new Result();
                $resultat->setIdUsers($this->getUser());
                $resultat->setAdressIp($request->getClientIp());
                $resultat->setAnswer($answersRepository->find($choiceId));
                $resultat->setIdQuestions($question);
                $entityManager->persist($resultat);
                $entityManager->flush();
            }
            return $this->redirectToRoute('questions_index');
        }

        return $this->render('questions/answer.html.twig', [
            'question' => $question,
        ]);
    }

    #[Route('/{id}', name: 'questions_delete', methods: ['POST'])]
    public function delete(Request $request, Questions $question): Response
    {
        if ($this->isCsrfTokenValid('delete' . $question->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($question);
            $entityManager->flush();
        }

        return $this->redirectToRoute('questions_index');
    }
}

templates/questions/_delete_form.html.twig
<form method="post" action="{{ path('questions_delete', {'id': question.id}) }}" onsubmit="return confirm('Etes vous sûr de vouloir supprimer la question ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ question.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/questions/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/questions/answer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Questions
{% endblock %}

{% block body %}
<div class="container-fluid">
	<h1>{{ question.libelle }}</h1>
	<form action="{{ path('questions_answer', {'id': question.id}) }}" method="post">
		{% set input_type = question.isMultiple ? 'checkbox' : 'radio' %}
		{% for answer in  question.answers %}
			<input type="{{input_type}}" name="answer[]" id="" value="{{answer.id}}">
			{{ answer.libelle }}
			<br>

		{% endfor %}
		<button>Valider</button>
	</form>

	<p>
		<a href="{{path('questions_index')}}">retour</a>
	</p>
</div>
{% endblock %}

templates/questions/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition des Questions{% endblock %}

{% block body %}
<div class="container-fluid">
    <h1>Edition des Questions</h1>

    {{ include('questions/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('questions_index') }}">Retour à la liste</a>

    {{ include('questions/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/questions/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes Questions{% endblock %}

{% block body %}
<div class="container-fluid">
	<h1>Mes Questions</h1>
	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Libelle</th>
				<th>Question multiple</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for question in questions %}
				<tr>
					<td>{{ question.id }}</td>
					<td>{{ question.libelle }}</td>
					<td>{{ question.isMultiple ? 'Oui' : 'Non' }}</td>
					<td>
						<a href="{{ path('answers_index', {'id': question.id}) }}">Réponse(s)</a>
						<a href="{{ path('questions_answer', {'id': question.id}) }}">Questionnaire</a>
		
						<a href="{{ path('questions_edit', {'id': question.id}) }}">Editer</a>
						<a href="{{ path('questions_result', {'id': question.id}) }}">Résultat</a>

						<a href="{{ path('questions_delete', {'id': question.id}) }}">Supprimer</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="5">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<a href="{{ path('questions_new') }}">Créer une nouvelle question</a>

	{% for message in app.flashes('success') %}
		<div class="alert alert-danger" role="alert">{{ message }}</div>
	{% endfor %}
</div>
{% endblock %}

templates/questions/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelles Questions{% endblock %}

{% block body %}
<div class="container-fluid">
    <h1>Créer une nouvelle question</h1>

    {{ include('questions/_form.html.twig') }}

    <a href="{{ path('questions_index') }}">retour à la liste</a>
</div>
{% endblock %}

templates/questions/result.html.twig
{% extends 'base.html.twig' %}

{% block title %}Questions
{% endblock %}

{% block body %}
<div class="container-fluid">
	<h1>{{ question.libelle }}</h1>
	{% for answer in  question.answers %}

		{{ answer.libelle }}

		{{ answer.results|length }}

		{# {{render_chart(chart)}} #}

		<br>

	{% endfor %}


	<p>
		<a href="{{path('questions_index')}}">retour</a>
	</p>
</div>
{% endblock %}

templates/questions/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Questions{% endblock %}


    <h1>Questions</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ question.id }}</td>
            </tr>
            <tr>
                <th>Libelle</th>
                <td>{{ question.libelle }}</td>
            </tr>
            <tr>
                <th>Is_multiple</th>
                <td>{{ question.isMultiple ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('questions_index') }}">back to list</a>

    <a href="{{ path('questions_edit', {'id': question.id}) }}">edit</a>

    {{ include('questions/_delete_form.html.twig') }}

templates/questions/stats.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-10 mt-4">
                <h1>Admin Dashboard</h1>
                {{render_chart(chart)}}
            </div>
        </div>
    </div>
{% endblock %}